services:
  postgres:
    image: postgres:latest
    container_name: flashcards-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flashcards
      POSTGRES_PASSWORD: flashcards
      POSTGRES_DB: flashcards_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
